name=GamepadCodec
version=1.0.1
author=chenliang@null-lab.com
maintainer=chenliang@null-lab.com
sentence=Encode and decode gamepad states over Stream using RobustFrame protocol.
paragraph=Encoder and Decoder for gamepad::input::State with RobustFrame framing and CRC.
category=Other
url=https://github.com/CodexPad/gamepad_codec_arduino_lib
architectures=*
includes=gamepad_codec_encoder.h,gamepad_codec_decoder.h
depends=RobustFrame (>=2.0.0),GamepadInput (>=1.2.1)
